import fs from 'fs'
import path from 'path'
import matter from 'gray-matter'
import Head from 'next/head'
import Post from '../componentes/Post'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({posts}) {

  //console.log(posts)
  return (
    <div>
      <Head>
        <title>Portafolio - MD - GitHub API</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='posts'>        
        {posts.map((post, index) => (          
          <Post key={index} post={post}/>
        ))}
      </div>
    </div>
  )
}


export async function getStaticProps() {

  // Obtiene los archivos del directorio posts
  const archivos = fs.readdirSync(path.join('posts'))
  

  const posts = archivos.map(archivo => {
  const slug = archivo.replace('.md', '')

  // Obtiene el stream
  const markdownDatos = fs.readFileSync(path.join('posts', archivo), 'utf-8')

  const { data: frontmatter } = matter(markdownDatos)
  //console.log(markdownDatos)

  return {
      slug, 
      frontmatter,
    }
  })
  
  //console.log(archivos)

  return {
    props: {
      posts,
    },
  }
}